### ISSUE TITLE
Help pyautogui for game

### ISSUE THREAD

**Issue by sadazs** [leonardobg/tft-bot#1]
Hi  leonardobg.
I try to learn from your code
I want to auto on an app, some time this app will display same a popup like capcha
Exp: 5+5x(2+1)=?
and have 3 answer to click
I take screenshot some question and
py.locateOnScreen("img/1.png")
py.moveto(x, y).click()

if I have 8 question (will take 8 img). How I can locate for img  question when it display, and loop for all
Thank so much

**Comment by leonardobg** [comment]
add me on discord and i will help you muttley#1434
